from datetime import datetime, timedelta
from pathlib import Path
import argparse
import math

SOLAR_TERM_NAME = [
    "小寒", "大寒", "立春", "雨水", "惊蛰", "春分",
    "清明", "谷雨", "立夏", "小满", "芒种", "夏至",
    "小暑", "大暑", "立秋", "处暑", "白露", "秋分",
    "寒露", "霜降", "立冬", "小雪", "大雪", "冬至"
]

START_YEAR = 1900
END_YEAR = 2100


def datetime_to_jd(dt_utc: datetime) -> float:
    year = dt_utc.year
    month = dt_utc.month
    day = dt_utc.day + (
        dt_utc.hour + (dt_utc.minute + (dt_utc.second + dt_utc.microsecond / 1_000_000.0) / 60.0) / 60.0
    ) / 24.0

    if month <= 2:
        year -= 1
        month += 12

    a = year // 100
    b = 2 - a + a // 4
    jd = int(365.25 * (year + 4716)) + int(30.6001 * (month + 1)) + day + b - 1524.5
    return jd


def delta_t_seconds(year: int, month: int) -> float:
    y = year + (month - 0.5) / 12.0
    if 1900 <= y < 1920:
        t = y - 1900
        return -2.79 + 1.494119 * t - 0.0598939 * t * t + 0.0061966 * t**3 - 0.000197 * t**4
    if 1920 <= y < 1941:
        t = y - 1920
        return 21.20 + 0.84493 * t - 0.076100 * t**2 + 0.0020936 * t**3
    if 1941 <= y < 1961:
        t = y - 1950
        return 29.07 + 0.407 * t - t**2 / 233.0 + t**3 / 2547.0
    if 1961 <= y < 1986:
        t = y - 1975
        return 45.45 + 1.067 * t - t**2 / 260.0 - t**3 / 718.0
    if 1986 <= y < 2005:
        t = y - 2000
        return (
            63.86
            + 0.3345 * t
            - 0.060374 * t**2
            + 0.0017275 * t**3
            + 0.000651814 * t**4
            + 0.00002373599 * t**5
        )
    if 2005 <= y < 2050:
        t = y - 2000
        return 62.92 + 0.32217 * t + 0.005589 * t**2

    t = (y - 1820) / 100.0
    return -20 + 32 * t * t


def solar_apparent_longitude_deg(dt_utc: datetime) -> float:
    jd_utc = datetime_to_jd(dt_utc)
    dt_sec = delta_t_seconds(dt_utc.year, dt_utc.month)
    jd_tt = jd_utc + dt_sec / 86400.0
    t = (jd_tt - 2451545.0) / 36525.0

    l0 = 280.46646 + 36000.76983 * t + 0.0003032 * t * t
    m = 357.52911 + 35999.05029 * t - 0.0001537 * t * t
    omega = 125.04 - 1934.136 * t

    m_rad = math.radians(m)
    c = (
        (1.914602 - 0.004817 * t - 0.000014 * t * t) * math.sin(m_rad)
        + (0.019993 - 0.000101 * t) * math.sin(2 * m_rad)
        + 0.000289 * math.sin(3 * m_rad)
    )

    true_long = l0 + c
    lambda_app = true_long - 0.00569 - 0.00478 * math.sin(math.radians(omega))
    return lambda_app % 360.0


def angle_diff_deg(a: float, b: float) -> float:
    return ((a - b + 540.0) % 360.0) - 180.0


def term_target_longitude(term_index: int) -> float:
    return (285.0 + 15.0 * term_index) % 360.0


def solve_term_time_utc(year: int, term_index: int) -> datetime:
    approx_month = term_index // 2 + 1
    approx_day = 6 if term_index % 2 == 0 else 21
    guess_bj = datetime(year, approx_month, approx_day, 12, 0, 0)
    guess_utc = guess_bj - timedelta(hours=8)

    target = term_target_longitude(term_index)

    def f(t: datetime) -> float:
        return angle_diff_deg(solar_apparent_longitude_deg(t), target)

    lo = guess_utc - timedelta(days=4)
    hi = guess_utc + timedelta(days=4)
    flo = f(lo)
    fhi = f(hi)

    for _ in range(10):
        if flo == 0.0 or fhi == 0.0 or flo * fhi <= 0.0:
            break
        lo -= timedelta(days=2)
        hi += timedelta(days=2)
        flo = f(lo)
        fhi = f(hi)

    if flo * fhi > 0.0:
        t = guess_utc
        for _ in range(20):
            diff = f(t)
            t -= timedelta(days=diff / 0.98564736)
        return t

    for _ in range(60):
        mid = lo + (hi - lo) / 2
        fmid = f(mid)
        if abs(fmid) < 1e-8:
            return mid
        if flo * fmid <= 0.0:
            hi = mid
            fhi = fmid
        else:
            lo = mid
            flo = fmid
    return lo + (hi - lo) / 2


def build_table(start_year: int = START_YEAR, end_year: int = END_YEAR):
    table = []
    for year in range(start_year, end_year + 1):
        year_row = []
        for i in range(24):
            dt_utc = solve_term_time_utc(year, i)
            dt_bj = dt_utc + timedelta(hours=8)
            year_row.append(dt_bj.day)
        table.append(year_row)
    return table


def to_cpp_inc(table, start_year: int = START_YEAR, end_year: int = END_YEAR) -> str:
    lines = []
    lines.append("// Auto-generated by SolarTermDay.py. Do not edit manually.")
    lines.append(f"constexpr int kSolarTermStartYear = {start_year};")
    lines.append(f"constexpr int kSolarTermEndYear = {end_year};")
    lines.append(f"constexpr uint8_t kSolarTermDay[{end_year - start_year + 1}][24] = {{")
    for row in table:
        lines.append("    {" + ", ".join(f"{d:2d}" for d in row) + "},")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate 1900-2100 solar term day lookup table for calendar_schedule.cc"
    )
    default_output = Path(__file__).with_name("solar_term_day_table.inc")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=default_output,
        help=f"Output file path (default: {default_output})",
    )
    args = parser.parse_args()

    table = build_table()
    content = to_cpp_inc(table)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(f"Generated: {args.output}")


if __name__ == "__main__":
    main()